// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: document.proto

package com.cloudera;

public final class DocumentProto {
  private DocumentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DocumentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 DocId = 1;
    boolean hasDocId();
    long getDocId();
    
    // optional .dremel.Document.Links links = 2;
    boolean hasLinks();
    com.cloudera.DocumentProto.Document.Links getLinks();
    com.cloudera.DocumentProto.Document.LinksOrBuilder getLinksOrBuilder();
    
    // repeated .dremel.Document.Name name = 3;
    java.util.List<com.cloudera.DocumentProto.Document.Name> 
        getNameList();
    com.cloudera.DocumentProto.Document.Name getName(int index);
    int getNameCount();
    java.util.List<? extends com.cloudera.DocumentProto.Document.NameOrBuilder> 
        getNameOrBuilderList();
    com.cloudera.DocumentProto.Document.NameOrBuilder getNameOrBuilder(
        int index);
  }
  public static final class Document extends
      com.google.protobuf.GeneratedMessage
      implements DocumentOrBuilder {
    // Use Document.newBuilder() to construct.
    private Document(Builder builder) {
      super(builder);
    }
    private Document(boolean noInit) {}
    
    private static final Document defaultInstance;
    public static Document getDefaultInstance() {
      return defaultInstance;
    }
    
    public Document getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudera.DocumentProto.internal_static_dremel_Document_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudera.DocumentProto.internal_static_dremel_Document_fieldAccessorTable;
    }
    
    public interface LinksOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated int64 Backward = 1;
      java.util.List<java.lang.Long> getBackwardList();
      int getBackwardCount();
      long getBackward(int index);
      
      // repeated int64 Forward = 2;
      java.util.List<java.lang.Long> getForwardList();
      int getForwardCount();
      long getForward(int index);
    }
    public static final class Links extends
        com.google.protobuf.GeneratedMessage
        implements LinksOrBuilder {
      // Use Links.newBuilder() to construct.
      private Links(Builder builder) {
        super(builder);
      }
      private Links(boolean noInit) {}
      
      private static final Links defaultInstance;
      public static Links getDefaultInstance() {
        return defaultInstance;
      }
      
      public Links getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudera.DocumentProto.internal_static_dremel_Document_Links_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudera.DocumentProto.internal_static_dremel_Document_Links_fieldAccessorTable;
      }
      
      // repeated int64 Backward = 1;
      public static final int BACKWARD_FIELD_NUMBER = 1;
      private java.util.List<java.lang.Long> backward_;
      public java.util.List<java.lang.Long>
          getBackwardList() {
        return backward_;
      }
      public int getBackwardCount() {
        return backward_.size();
      }
      public long getBackward(int index) {
        return backward_.get(index);
      }
      
      // repeated int64 Forward = 2;
      public static final int FORWARD_FIELD_NUMBER = 2;
      private java.util.List<java.lang.Long> forward_;
      public java.util.List<java.lang.Long>
          getForwardList() {
        return forward_;
      }
      public int getForwardCount() {
        return forward_.size();
      }
      public long getForward(int index) {
        return forward_.get(index);
      }
      
      private void initFields() {
        backward_ = java.util.Collections.emptyList();;
        forward_ = java.util.Collections.emptyList();;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < backward_.size(); i++) {
          output.writeInt64(1, backward_.get(i));
        }
        for (int i = 0; i < forward_.size(); i++) {
          output.writeInt64(2, forward_.get(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < backward_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt64SizeNoTag(backward_.get(i));
          }
          size += dataSize;
          size += 1 * getBackwardList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < forward_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt64SizeNoTag(forward_.get(i));
          }
          size += dataSize;
          size += 1 * getForwardList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.cloudera.DocumentProto.Document.Links parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cloudera.DocumentProto.Document.Links parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Links parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.cloudera.DocumentProto.Document.Links prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.cloudera.DocumentProto.Document.LinksOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cloudera.DocumentProto.internal_static_dremel_Document_Links_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cloudera.DocumentProto.internal_static_dremel_Document_Links_fieldAccessorTable;
        }
        
        // Construct using com.cloudera.DocumentProto.Document.Links.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          backward_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000001);
          forward_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cloudera.DocumentProto.Document.Links.getDescriptor();
        }
        
        public com.cloudera.DocumentProto.Document.Links getDefaultInstanceForType() {
          return com.cloudera.DocumentProto.Document.Links.getDefaultInstance();
        }
        
        public com.cloudera.DocumentProto.Document.Links build() {
          com.cloudera.DocumentProto.Document.Links result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.cloudera.DocumentProto.Document.Links buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.cloudera.DocumentProto.Document.Links result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.cloudera.DocumentProto.Document.Links buildPartial() {
          com.cloudera.DocumentProto.Document.Links result = new com.cloudera.DocumentProto.Document.Links(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            backward_ = java.util.Collections.unmodifiableList(backward_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.backward_ = backward_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            forward_ = java.util.Collections.unmodifiableList(forward_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.forward_ = forward_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cloudera.DocumentProto.Document.Links) {
            return mergeFrom((com.cloudera.DocumentProto.Document.Links)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.cloudera.DocumentProto.Document.Links other) {
          if (other == com.cloudera.DocumentProto.Document.Links.getDefaultInstance()) return this;
          if (!other.backward_.isEmpty()) {
            if (backward_.isEmpty()) {
              backward_ = other.backward_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBackwardIsMutable();
              backward_.addAll(other.backward_);
            }
            onChanged();
          }
          if (!other.forward_.isEmpty()) {
            if (forward_.isEmpty()) {
              forward_ = other.forward_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureForwardIsMutable();
              forward_.addAll(other.forward_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                ensureBackwardIsMutable();
                backward_.add(input.readInt64());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                while (input.getBytesUntilLimit() > 0) {
                  addBackward(input.readInt64());
                }
                input.popLimit(limit);
                break;
              }
              case 16: {
                ensureForwardIsMutable();
                forward_.add(input.readInt64());
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                while (input.getBytesUntilLimit() > 0) {
                  addForward(input.readInt64());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated int64 Backward = 1;
        private java.util.List<java.lang.Long> backward_ = java.util.Collections.emptyList();;
        private void ensureBackwardIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            backward_ = new java.util.ArrayList<java.lang.Long>(backward_);
            bitField0_ |= 0x00000001;
           }
        }
        public java.util.List<java.lang.Long>
            getBackwardList() {
          return java.util.Collections.unmodifiableList(backward_);
        }
        public int getBackwardCount() {
          return backward_.size();
        }
        public long getBackward(int index) {
          return backward_.get(index);
        }
        public Builder setBackward(
            int index, long value) {
          ensureBackwardIsMutable();
          backward_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addBackward(long value) {
          ensureBackwardIsMutable();
          backward_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllBackward(
            java.lang.Iterable<? extends java.lang.Long> values) {
          ensureBackwardIsMutable();
          super.addAll(values, backward_);
          onChanged();
          return this;
        }
        public Builder clearBackward() {
          backward_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        
        // repeated int64 Forward = 2;
        private java.util.List<java.lang.Long> forward_ = java.util.Collections.emptyList();;
        private void ensureForwardIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            forward_ = new java.util.ArrayList<java.lang.Long>(forward_);
            bitField0_ |= 0x00000002;
           }
        }
        public java.util.List<java.lang.Long>
            getForwardList() {
          return java.util.Collections.unmodifiableList(forward_);
        }
        public int getForwardCount() {
          return forward_.size();
        }
        public long getForward(int index) {
          return forward_.get(index);
        }
        public Builder setForward(
            int index, long value) {
          ensureForwardIsMutable();
          forward_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addForward(long value) {
          ensureForwardIsMutable();
          forward_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllForward(
            java.lang.Iterable<? extends java.lang.Long> values) {
          ensureForwardIsMutable();
          super.addAll(values, forward_);
          onChanged();
          return this;
        }
        public Builder clearForward() {
          forward_ = java.util.Collections.emptyList();;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:dremel.Document.Links)
      }
      
      static {
        defaultInstance = new Links(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:dremel.Document.Links)
    }
    
    public interface NameOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated .dremel.Document.Name.Language language = 1;
      java.util.List<com.cloudera.DocumentProto.Document.Name.Language> 
          getLanguageList();
      com.cloudera.DocumentProto.Document.Name.Language getLanguage(int index);
      int getLanguageCount();
      java.util.List<? extends com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder> 
          getLanguageOrBuilderList();
      com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder getLanguageOrBuilder(
          int index);
      
      // optional string Url = 2;
      boolean hasUrl();
      String getUrl();
    }
    public static final class Name extends
        com.google.protobuf.GeneratedMessage
        implements NameOrBuilder {
      // Use Name.newBuilder() to construct.
      private Name(Builder builder) {
        super(builder);
      }
      private Name(boolean noInit) {}
      
      private static final Name defaultInstance;
      public static Name getDefaultInstance() {
        return defaultInstance;
      }
      
      public Name getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_fieldAccessorTable;
      }
      
      public interface LanguageOrBuilder
          extends com.google.protobuf.MessageOrBuilder {
        
        // required string Code = 1;
        boolean hasCode();
        String getCode();
        
        // optional string Country = 2;
        boolean hasCountry();
        String getCountry();
      }
      public static final class Language extends
          com.google.protobuf.GeneratedMessage
          implements LanguageOrBuilder {
        // Use Language.newBuilder() to construct.
        private Language(Builder builder) {
          super(builder);
        }
        private Language(boolean noInit) {}
        
        private static final Language defaultInstance;
        public static Language getDefaultInstance() {
          return defaultInstance;
        }
        
        public Language getDefaultInstanceForType() {
          return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_Language_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_Language_fieldAccessorTable;
        }
        
        private int bitField0_;
        // required string Code = 1;
        public static final int CODE_FIELD_NUMBER = 1;
        private java.lang.Object code_;
        public boolean hasCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getCode() {
          java.lang.Object ref = code_;
          if (ref instanceof String) {
            return (String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (com.google.protobuf.Internal.isValidUtf8(bs)) {
              code_ = s;
            }
            return s;
          }
        }
        private com.google.protobuf.ByteString getCodeBytes() {
          java.lang.Object ref = code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8((String) ref);
            code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        
        // optional string Country = 2;
        public static final int COUNTRY_FIELD_NUMBER = 2;
        private java.lang.Object country_;
        public boolean hasCountry() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getCountry() {
          java.lang.Object ref = country_;
          if (ref instanceof String) {
            return (String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (com.google.protobuf.Internal.isValidUtf8(bs)) {
              country_ = s;
            }
            return s;
          }
        }
        private com.google.protobuf.ByteString getCountryBytes() {
          java.lang.Object ref = country_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8((String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        
        private void initFields() {
          code_ = "";
          country_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;
          
          if (!hasCode()) {
            memoizedIsInitialized = 0;
            return false;
          }
          memoizedIsInitialized = 1;
          return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getCodeBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeBytes(2, getCountryBytes());
          }
          getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
        
          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getCodeBytes());
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(2, getCountryBytes());
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }
        
        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }
        
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.cloudera.DocumentProto.Document.Name.Language parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        
        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.cloudera.DocumentProto.Document.Name.Language prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }
        
        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_Language_descriptor;
          }
          
          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_Language_fieldAccessorTable;
          }
          
          // Construct using com.cloudera.DocumentProto.Document.Name.Language.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }
          
          private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }
          
          public Builder clear() {
            super.clear();
            code_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            country_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }
          
          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }
          
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.cloudera.DocumentProto.Document.Name.Language.getDescriptor();
          }
          
          public com.cloudera.DocumentProto.Document.Name.Language getDefaultInstanceForType() {
            return com.cloudera.DocumentProto.Document.Name.Language.getDefaultInstance();
          }
          
          public com.cloudera.DocumentProto.Document.Name.Language build() {
            com.cloudera.DocumentProto.Document.Name.Language result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }
          
          private com.cloudera.DocumentProto.Document.Name.Language buildParsed()
              throws com.google.protobuf.InvalidProtocolBufferException {
            com.cloudera.DocumentProto.Document.Name.Language result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(
                result).asInvalidProtocolBufferException();
            }
            return result;
          }
          
          public com.cloudera.DocumentProto.Document.Name.Language buildPartial() {
            com.cloudera.DocumentProto.Document.Name.Language result = new com.cloudera.DocumentProto.Document.Name.Language(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.code_ = code_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.country_ = country_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }
          
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.cloudera.DocumentProto.Document.Name.Language) {
              return mergeFrom((com.cloudera.DocumentProto.Document.Name.Language)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }
          
          public Builder mergeFrom(com.cloudera.DocumentProto.Document.Name.Language other) {
            if (other == com.cloudera.DocumentProto.Document.Name.Language.getDefaultInstance()) return this;
            if (other.hasCode()) {
              setCode(other.getCode());
            }
            if (other.hasCountry()) {
              setCountry(other.getCountry());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }
          
          public final boolean isInitialized() {
            if (!hasCode()) {
              
              return false;
            }
            return true;
          }
          
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder(
                this.getUnknownFields());
            while (true) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    this.setUnknownFields(unknownFields.build());
                    onChanged();
                    return this;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  code_ = input.readBytes();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  country_ = input.readBytes();
                  break;
                }
              }
            }
          }
          
          private int bitField0_;
          
          // required string Code = 1;
          private java.lang.Object code_ = "";
          public boolean hasCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          public String getCode() {
            java.lang.Object ref = code_;
            if (!(ref instanceof String)) {
              String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
              code_ = s;
              return s;
            } else {
              return (String) ref;
            }
          }
          public Builder setCode(String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            code_ = value;
            onChanged();
            return this;
          }
          public Builder clearCode() {
            bitField0_ = (bitField0_ & ~0x00000001);
            code_ = getDefaultInstance().getCode();
            onChanged();
            return this;
          }
          void setCode(com.google.protobuf.ByteString value) {
            bitField0_ |= 0x00000001;
            code_ = value;
            onChanged();
          }
          
          // optional string Country = 2;
          private java.lang.Object country_ = "";
          public boolean hasCountry() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          public String getCountry() {
            java.lang.Object ref = country_;
            if (!(ref instanceof String)) {
              String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
              country_ = s;
              return s;
            } else {
              return (String) ref;
            }
          }
          public Builder setCountry(String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            country_ = value;
            onChanged();
            return this;
          }
          public Builder clearCountry() {
            bitField0_ = (bitField0_ & ~0x00000002);
            country_ = getDefaultInstance().getCountry();
            onChanged();
            return this;
          }
          void setCountry(com.google.protobuf.ByteString value) {
            bitField0_ |= 0x00000002;
            country_ = value;
            onChanged();
          }
          
          // @@protoc_insertion_point(builder_scope:dremel.Document.Name.Language)
        }
        
        static {
          defaultInstance = new Language(true);
          defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:dremel.Document.Name.Language)
      }
      
      private int bitField0_;
      // repeated .dremel.Document.Name.Language language = 1;
      public static final int LANGUAGE_FIELD_NUMBER = 1;
      private java.util.List<com.cloudera.DocumentProto.Document.Name.Language> language_;
      public java.util.List<com.cloudera.DocumentProto.Document.Name.Language> getLanguageList() {
        return language_;
      }
      public java.util.List<? extends com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder> 
          getLanguageOrBuilderList() {
        return language_;
      }
      public int getLanguageCount() {
        return language_.size();
      }
      public com.cloudera.DocumentProto.Document.Name.Language getLanguage(int index) {
        return language_.get(index);
      }
      public com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder getLanguageOrBuilder(
          int index) {
        return language_.get(index);
      }
      
      // optional string Url = 2;
      public static final int URL_FIELD_NUMBER = 2;
      private java.lang.Object url_;
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            url_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        language_ = java.util.Collections.emptyList();
        url_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        for (int i = 0; i < getLanguageCount(); i++) {
          if (!getLanguage(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < language_.size(); i++) {
          output.writeMessage(1, language_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(2, getUrlBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        for (int i = 0; i < language_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, language_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getUrlBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.cloudera.DocumentProto.Document.Name parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cloudera.DocumentProto.Document.Name parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.cloudera.DocumentProto.Document.Name parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.cloudera.DocumentProto.Document.Name prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.cloudera.DocumentProto.Document.NameOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.cloudera.DocumentProto.internal_static_dremel_Document_Name_fieldAccessorTable;
        }
        
        // Construct using com.cloudera.DocumentProto.Document.Name.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getLanguageFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (languageBuilder_ == null) {
            language_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            languageBuilder_.clear();
          }
          url_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.cloudera.DocumentProto.Document.Name.getDescriptor();
        }
        
        public com.cloudera.DocumentProto.Document.Name getDefaultInstanceForType() {
          return com.cloudera.DocumentProto.Document.Name.getDefaultInstance();
        }
        
        public com.cloudera.DocumentProto.Document.Name build() {
          com.cloudera.DocumentProto.Document.Name result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.cloudera.DocumentProto.Document.Name buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.cloudera.DocumentProto.Document.Name result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.cloudera.DocumentProto.Document.Name buildPartial() {
          com.cloudera.DocumentProto.Document.Name result = new com.cloudera.DocumentProto.Document.Name(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (languageBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              language_ = java.util.Collections.unmodifiableList(language_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.language_ = language_;
          } else {
            result.language_ = languageBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000001;
          }
          result.url_ = url_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.cloudera.DocumentProto.Document.Name) {
            return mergeFrom((com.cloudera.DocumentProto.Document.Name)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.cloudera.DocumentProto.Document.Name other) {
          if (other == com.cloudera.DocumentProto.Document.Name.getDefaultInstance()) return this;
          if (languageBuilder_ == null) {
            if (!other.language_.isEmpty()) {
              if (language_.isEmpty()) {
                language_ = other.language_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureLanguageIsMutable();
                language_.addAll(other.language_);
              }
              onChanged();
            }
          } else {
            if (!other.language_.isEmpty()) {
              if (languageBuilder_.isEmpty()) {
                languageBuilder_.dispose();
                languageBuilder_ = null;
                language_ = other.language_;
                bitField0_ = (bitField0_ & ~0x00000001);
                languageBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getLanguageFieldBuilder() : null;
              } else {
                languageBuilder_.addAllMessages(other.language_);
              }
            }
          }
          if (other.hasUrl()) {
            setUrl(other.getUrl());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          for (int i = 0; i < getLanguageCount(); i++) {
            if (!getLanguage(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                com.cloudera.DocumentProto.Document.Name.Language.Builder subBuilder = com.cloudera.DocumentProto.Document.Name.Language.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addLanguage(subBuilder.buildPartial());
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                url_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated .dremel.Document.Name.Language language = 1;
        private java.util.List<com.cloudera.DocumentProto.Document.Name.Language> language_ =
          java.util.Collections.emptyList();
        private void ensureLanguageIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            language_ = new java.util.ArrayList<com.cloudera.DocumentProto.Document.Name.Language>(language_);
            bitField0_ |= 0x00000001;
           }
        }
        
        private com.google.protobuf.RepeatedFieldBuilder<
            com.cloudera.DocumentProto.Document.Name.Language, com.cloudera.DocumentProto.Document.Name.Language.Builder, com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder> languageBuilder_;
        
        public java.util.List<com.cloudera.DocumentProto.Document.Name.Language> getLanguageList() {
          if (languageBuilder_ == null) {
            return java.util.Collections.unmodifiableList(language_);
          } else {
            return languageBuilder_.getMessageList();
          }
        }
        public int getLanguageCount() {
          if (languageBuilder_ == null) {
            return language_.size();
          } else {
            return languageBuilder_.getCount();
          }
        }
        public com.cloudera.DocumentProto.Document.Name.Language getLanguage(int index) {
          if (languageBuilder_ == null) {
            return language_.get(index);
          } else {
            return languageBuilder_.getMessage(index);
          }
        }
        public Builder setLanguage(
            int index, com.cloudera.DocumentProto.Document.Name.Language value) {
          if (languageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureLanguageIsMutable();
            language_.set(index, value);
            onChanged();
          } else {
            languageBuilder_.setMessage(index, value);
          }
          return this;
        }
        public Builder setLanguage(
            int index, com.cloudera.DocumentProto.Document.Name.Language.Builder builderForValue) {
          if (languageBuilder_ == null) {
            ensureLanguageIsMutable();
            language_.set(index, builderForValue.build());
            onChanged();
          } else {
            languageBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addLanguage(com.cloudera.DocumentProto.Document.Name.Language value) {
          if (languageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureLanguageIsMutable();
            language_.add(value);
            onChanged();
          } else {
            languageBuilder_.addMessage(value);
          }
          return this;
        }
        public Builder addLanguage(
            int index, com.cloudera.DocumentProto.Document.Name.Language value) {
          if (languageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureLanguageIsMutable();
            language_.add(index, value);
            onChanged();
          } else {
            languageBuilder_.addMessage(index, value);
          }
          return this;
        }
        public Builder addLanguage(
            com.cloudera.DocumentProto.Document.Name.Language.Builder builderForValue) {
          if (languageBuilder_ == null) {
            ensureLanguageIsMutable();
            language_.add(builderForValue.build());
            onChanged();
          } else {
            languageBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        public Builder addLanguage(
            int index, com.cloudera.DocumentProto.Document.Name.Language.Builder builderForValue) {
          if (languageBuilder_ == null) {
            ensureLanguageIsMutable();
            language_.add(index, builderForValue.build());
            onChanged();
          } else {
            languageBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addAllLanguage(
            java.lang.Iterable<? extends com.cloudera.DocumentProto.Document.Name.Language> values) {
          if (languageBuilder_ == null) {
            ensureLanguageIsMutable();
            super.addAll(values, language_);
            onChanged();
          } else {
            languageBuilder_.addAllMessages(values);
          }
          return this;
        }
        public Builder clearLanguage() {
          if (languageBuilder_ == null) {
            language_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            languageBuilder_.clear();
          }
          return this;
        }
        public Builder removeLanguage(int index) {
          if (languageBuilder_ == null) {
            ensureLanguageIsMutable();
            language_.remove(index);
            onChanged();
          } else {
            languageBuilder_.remove(index);
          }
          return this;
        }
        public com.cloudera.DocumentProto.Document.Name.Language.Builder getLanguageBuilder(
            int index) {
          return getLanguageFieldBuilder().getBuilder(index);
        }
        public com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder getLanguageOrBuilder(
            int index) {
          if (languageBuilder_ == null) {
            return language_.get(index);  } else {
            return languageBuilder_.getMessageOrBuilder(index);
          }
        }
        public java.util.List<? extends com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder> 
             getLanguageOrBuilderList() {
          if (languageBuilder_ != null) {
            return languageBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(language_);
          }
        }
        public com.cloudera.DocumentProto.Document.Name.Language.Builder addLanguageBuilder() {
          return getLanguageFieldBuilder().addBuilder(
              com.cloudera.DocumentProto.Document.Name.Language.getDefaultInstance());
        }
        public com.cloudera.DocumentProto.Document.Name.Language.Builder addLanguageBuilder(
            int index) {
          return getLanguageFieldBuilder().addBuilder(
              index, com.cloudera.DocumentProto.Document.Name.Language.getDefaultInstance());
        }
        public java.util.List<com.cloudera.DocumentProto.Document.Name.Language.Builder> 
             getLanguageBuilderList() {
          return getLanguageFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            com.cloudera.DocumentProto.Document.Name.Language, com.cloudera.DocumentProto.Document.Name.Language.Builder, com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder> 
            getLanguageFieldBuilder() {
          if (languageBuilder_ == null) {
            languageBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                com.cloudera.DocumentProto.Document.Name.Language, com.cloudera.DocumentProto.Document.Name.Language.Builder, com.cloudera.DocumentProto.Document.Name.LanguageOrBuilder>(
                    language_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            language_ = null;
          }
          return languageBuilder_;
        }
        
        // optional string Url = 2;
        private java.lang.Object url_ = "";
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            url_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setUrl(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          url_ = value;
          onChanged();
          return this;
        }
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000002);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        void setUrl(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          url_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:dremel.Document.Name)
      }
      
      static {
        defaultInstance = new Name(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:dremel.Document.Name)
    }
    
    private int bitField0_;
    // required int64 DocId = 1;
    public static final int DOCID_FIELD_NUMBER = 1;
    private long docId_;
    public boolean hasDocId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getDocId() {
      return docId_;
    }
    
    // optional .dremel.Document.Links links = 2;
    public static final int LINKS_FIELD_NUMBER = 2;
    private com.cloudera.DocumentProto.Document.Links links_;
    public boolean hasLinks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.cloudera.DocumentProto.Document.Links getLinks() {
      return links_;
    }
    public com.cloudera.DocumentProto.Document.LinksOrBuilder getLinksOrBuilder() {
      return links_;
    }
    
    // repeated .dremel.Document.Name name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.util.List<com.cloudera.DocumentProto.Document.Name> name_;
    public java.util.List<com.cloudera.DocumentProto.Document.Name> getNameList() {
      return name_;
    }
    public java.util.List<? extends com.cloudera.DocumentProto.Document.NameOrBuilder> 
        getNameOrBuilderList() {
      return name_;
    }
    public int getNameCount() {
      return name_.size();
    }
    public com.cloudera.DocumentProto.Document.Name getName(int index) {
      return name_.get(index);
    }
    public com.cloudera.DocumentProto.Document.NameOrBuilder getNameOrBuilder(
        int index) {
      return name_.get(index);
    }
    
    private void initFields() {
      docId_ = 0L;
      links_ = com.cloudera.DocumentProto.Document.Links.getDefaultInstance();
      name_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDocId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getNameCount(); i++) {
        if (!getName(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, docId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, links_);
      }
      for (int i = 0; i < name_.size(); i++) {
        output.writeMessage(3, name_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, docId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, links_);
      }
      for (int i = 0; i < name_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, name_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudera.DocumentProto.Document parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudera.DocumentProto.Document parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudera.DocumentProto.Document parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudera.DocumentProto.Document parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudera.DocumentProto.Document prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudera.DocumentProto.DocumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudera.DocumentProto.internal_static_dremel_Document_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudera.DocumentProto.internal_static_dremel_Document_fieldAccessorTable;
      }
      
      // Construct using com.cloudera.DocumentProto.Document.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLinksFieldBuilder();
          getNameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        docId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (linksBuilder_ == null) {
          links_ = com.cloudera.DocumentProto.Document.Links.getDefaultInstance();
        } else {
          linksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (nameBuilder_ == null) {
          name_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          nameBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudera.DocumentProto.Document.getDescriptor();
      }
      
      public com.cloudera.DocumentProto.Document getDefaultInstanceForType() {
        return com.cloudera.DocumentProto.Document.getDefaultInstance();
      }
      
      public com.cloudera.DocumentProto.Document build() {
        com.cloudera.DocumentProto.Document result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudera.DocumentProto.Document buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudera.DocumentProto.Document result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudera.DocumentProto.Document buildPartial() {
        com.cloudera.DocumentProto.Document result = new com.cloudera.DocumentProto.Document(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.docId_ = docId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (linksBuilder_ == null) {
          result.links_ = links_;
        } else {
          result.links_ = linksBuilder_.build();
        }
        if (nameBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            name_ = java.util.Collections.unmodifiableList(name_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudera.DocumentProto.Document) {
          return mergeFrom((com.cloudera.DocumentProto.Document)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudera.DocumentProto.Document other) {
        if (other == com.cloudera.DocumentProto.Document.getDefaultInstance()) return this;
        if (other.hasDocId()) {
          setDocId(other.getDocId());
        }
        if (other.hasLinks()) {
          mergeLinks(other.getLinks());
        }
        if (nameBuilder_ == null) {
          if (!other.name_.isEmpty()) {
            if (name_.isEmpty()) {
              name_ = other.name_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureNameIsMutable();
              name_.addAll(other.name_);
            }
            onChanged();
          }
        } else {
          if (!other.name_.isEmpty()) {
            if (nameBuilder_.isEmpty()) {
              nameBuilder_.dispose();
              nameBuilder_ = null;
              name_ = other.name_;
              bitField0_ = (bitField0_ & ~0x00000004);
              nameBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNameFieldBuilder() : null;
            } else {
              nameBuilder_.addAllMessages(other.name_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDocId()) {
          
          return false;
        }
        for (int i = 0; i < getNameCount(); i++) {
          if (!getName(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              docId_ = input.readInt64();
              break;
            }
            case 18: {
              com.cloudera.DocumentProto.Document.Links.Builder subBuilder = com.cloudera.DocumentProto.Document.Links.newBuilder();
              if (hasLinks()) {
                subBuilder.mergeFrom(getLinks());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLinks(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.cloudera.DocumentProto.Document.Name.Builder subBuilder = com.cloudera.DocumentProto.Document.Name.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addName(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 DocId = 1;
      private long docId_ ;
      public boolean hasDocId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getDocId() {
        return docId_;
      }
      public Builder setDocId(long value) {
        bitField0_ |= 0x00000001;
        docId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDocId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        docId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .dremel.Document.Links links = 2;
      private com.cloudera.DocumentProto.Document.Links links_ = com.cloudera.DocumentProto.Document.Links.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudera.DocumentProto.Document.Links, com.cloudera.DocumentProto.Document.Links.Builder, com.cloudera.DocumentProto.Document.LinksOrBuilder> linksBuilder_;
      public boolean hasLinks() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.cloudera.DocumentProto.Document.Links getLinks() {
        if (linksBuilder_ == null) {
          return links_;
        } else {
          return linksBuilder_.getMessage();
        }
      }
      public Builder setLinks(com.cloudera.DocumentProto.Document.Links value) {
        if (linksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          links_ = value;
          onChanged();
        } else {
          linksBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setLinks(
          com.cloudera.DocumentProto.Document.Links.Builder builderForValue) {
        if (linksBuilder_ == null) {
          links_ = builderForValue.build();
          onChanged();
        } else {
          linksBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeLinks(com.cloudera.DocumentProto.Document.Links value) {
        if (linksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              links_ != com.cloudera.DocumentProto.Document.Links.getDefaultInstance()) {
            links_ =
              com.cloudera.DocumentProto.Document.Links.newBuilder(links_).mergeFrom(value).buildPartial();
          } else {
            links_ = value;
          }
          onChanged();
        } else {
          linksBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearLinks() {
        if (linksBuilder_ == null) {
          links_ = com.cloudera.DocumentProto.Document.Links.getDefaultInstance();
          onChanged();
        } else {
          linksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.cloudera.DocumentProto.Document.Links.Builder getLinksBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLinksFieldBuilder().getBuilder();
      }
      public com.cloudera.DocumentProto.Document.LinksOrBuilder getLinksOrBuilder() {
        if (linksBuilder_ != null) {
          return linksBuilder_.getMessageOrBuilder();
        } else {
          return links_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudera.DocumentProto.Document.Links, com.cloudera.DocumentProto.Document.Links.Builder, com.cloudera.DocumentProto.Document.LinksOrBuilder> 
          getLinksFieldBuilder() {
        if (linksBuilder_ == null) {
          linksBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cloudera.DocumentProto.Document.Links, com.cloudera.DocumentProto.Document.Links.Builder, com.cloudera.DocumentProto.Document.LinksOrBuilder>(
                  links_,
                  getParentForChildren(),
                  isClean());
          links_ = null;
        }
        return linksBuilder_;
      }
      
      // repeated .dremel.Document.Name name = 3;
      private java.util.List<com.cloudera.DocumentProto.Document.Name> name_ =
        java.util.Collections.emptyList();
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          name_ = new java.util.ArrayList<com.cloudera.DocumentProto.Document.Name>(name_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cloudera.DocumentProto.Document.Name, com.cloudera.DocumentProto.Document.Name.Builder, com.cloudera.DocumentProto.Document.NameOrBuilder> nameBuilder_;
      
      public java.util.List<com.cloudera.DocumentProto.Document.Name> getNameList() {
        if (nameBuilder_ == null) {
          return java.util.Collections.unmodifiableList(name_);
        } else {
          return nameBuilder_.getMessageList();
        }
      }
      public int getNameCount() {
        if (nameBuilder_ == null) {
          return name_.size();
        } else {
          return nameBuilder_.getCount();
        }
      }
      public com.cloudera.DocumentProto.Document.Name getName(int index) {
        if (nameBuilder_ == null) {
          return name_.get(index);
        } else {
          return nameBuilder_.getMessage(index);
        }
      }
      public Builder setName(
          int index, com.cloudera.DocumentProto.Document.Name value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNameIsMutable();
          name_.set(index, value);
          onChanged();
        } else {
          nameBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setName(
          int index, com.cloudera.DocumentProto.Document.Name.Builder builderForValue) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.set(index, builderForValue.build());
          onChanged();
        } else {
          nameBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addName(com.cloudera.DocumentProto.Document.Name value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNameIsMutable();
          name_.add(value);
          onChanged();
        } else {
          nameBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addName(
          int index, com.cloudera.DocumentProto.Document.Name value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNameIsMutable();
          name_.add(index, value);
          onChanged();
        } else {
          nameBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addName(
          com.cloudera.DocumentProto.Document.Name.Builder builderForValue) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.add(builderForValue.build());
          onChanged();
        } else {
          nameBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addName(
          int index, com.cloudera.DocumentProto.Document.Name.Builder builderForValue) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.add(index, builderForValue.build());
          onChanged();
        } else {
          nameBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllName(
          java.lang.Iterable<? extends com.cloudera.DocumentProto.Document.Name> values) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          super.addAll(values, name_);
          onChanged();
        } else {
          nameBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          nameBuilder_.clear();
        }
        return this;
      }
      public Builder removeName(int index) {
        if (nameBuilder_ == null) {
          ensureNameIsMutable();
          name_.remove(index);
          onChanged();
        } else {
          nameBuilder_.remove(index);
        }
        return this;
      }
      public com.cloudera.DocumentProto.Document.Name.Builder getNameBuilder(
          int index) {
        return getNameFieldBuilder().getBuilder(index);
      }
      public com.cloudera.DocumentProto.Document.NameOrBuilder getNameOrBuilder(
          int index) {
        if (nameBuilder_ == null) {
          return name_.get(index);  } else {
          return nameBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.cloudera.DocumentProto.Document.NameOrBuilder> 
           getNameOrBuilderList() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(name_);
        }
      }
      public com.cloudera.DocumentProto.Document.Name.Builder addNameBuilder() {
        return getNameFieldBuilder().addBuilder(
            com.cloudera.DocumentProto.Document.Name.getDefaultInstance());
      }
      public com.cloudera.DocumentProto.Document.Name.Builder addNameBuilder(
          int index) {
        return getNameFieldBuilder().addBuilder(
            index, com.cloudera.DocumentProto.Document.Name.getDefaultInstance());
      }
      public java.util.List<com.cloudera.DocumentProto.Document.Name.Builder> 
           getNameBuilderList() {
        return getNameFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cloudera.DocumentProto.Document.Name, com.cloudera.DocumentProto.Document.Name.Builder, com.cloudera.DocumentProto.Document.NameOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cloudera.DocumentProto.Document.Name, com.cloudera.DocumentProto.Document.Name.Builder, com.cloudera.DocumentProto.Document.NameOrBuilder>(
                  name_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:dremel.Document)
    }
    
    static {
      defaultInstance = new Document(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:dremel.Document)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dremel_Document_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dremel_Document_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dremel_Document_Links_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dremel_Document_Links_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dremel_Document_Name_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dremel_Document_Name_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dremel_Document_Name_Language_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dremel_Document_Name_Language_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016document.proto\022\006dremel\"\203\002\n\010Document\022\r\n" +
      "\005DocId\030\001 \002(\003\022%\n\005links\030\002 \001(\0132\026.dremel.Doc" +
      "ument.Links\022#\n\004name\030\003 \003(\0132\025.dremel.Docum" +
      "ent.Name\032*\n\005Links\022\020\n\010Backward\030\001 \003(\003\022\017\n\007F" +
      "orward\030\002 \003(\003\032p\n\004Name\0220\n\010language\030\001 \003(\0132\036" +
      ".dremel.Document.Name.Language\022\013\n\003Url\030\002 " +
      "\001(\t\032)\n\010Language\022\014\n\004Code\030\001 \002(\t\022\017\n\007Country" +
      "\030\002 \001(\tB\035\n\014com.clouderaB\rDocumentProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dremel_Document_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dremel_Document_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dremel_Document_descriptor,
              new java.lang.String[] { "DocId", "Links", "Name", },
              com.cloudera.DocumentProto.Document.class,
              com.cloudera.DocumentProto.Document.Builder.class);
          internal_static_dremel_Document_Links_descriptor =
            internal_static_dremel_Document_descriptor.getNestedTypes().get(0);
          internal_static_dremel_Document_Links_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dremel_Document_Links_descriptor,
              new java.lang.String[] { "Backward", "Forward", },
              com.cloudera.DocumentProto.Document.Links.class,
              com.cloudera.DocumentProto.Document.Links.Builder.class);
          internal_static_dremel_Document_Name_descriptor =
            internal_static_dremel_Document_descriptor.getNestedTypes().get(1);
          internal_static_dremel_Document_Name_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dremel_Document_Name_descriptor,
              new java.lang.String[] { "Language", "Url", },
              com.cloudera.DocumentProto.Document.Name.class,
              com.cloudera.DocumentProto.Document.Name.Builder.class);
          internal_static_dremel_Document_Name_Language_descriptor =
            internal_static_dremel_Document_Name_descriptor.getNestedTypes().get(0);
          internal_static_dremel_Document_Name_Language_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dremel_Document_Name_Language_descriptor,
              new java.lang.String[] { "Code", "Country", },
              com.cloudera.DocumentProto.Document.Name.Language.class,
              com.cloudera.DocumentProto.Document.Name.Language.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
